# Generated by Django 2.0.3 on 2018-04-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[(1, 'Type1'), (2, 'Type2'), (3, 'Type3')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('doc_status', models.CharField(choices=[(1, 'Primit'), (2, 'Acceptat'), (3, 'Respins'), (4, 'In Asteptare')], default=(1, 'Primit'), max_length=2)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents_updated_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='document.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='pack_status',
            field=models.CharField(choices=[(1, 'Status1'), (2, 'Status2'), (3, 'Status3')], default=(1, 'Status1'), max_length=2),
        ),
    ]
