# Generated by Django 2.0.3 on 2018-04-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20180415_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='description',
            new_name='comments',
        ),
    ]
