# Generated by Django 2.0.3 on 2018-04-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20180418_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_documents', to='document.Package'),
        ),
    ]
